name = "CompHENS"
uuid = "873a7a81-90fd-4468-8feb-46a7ba58f008"
authors = ["Avinash Subramanian"]
version = "0.2"

[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Kwonly = "18d08c8c-0732-55ee-a446-91a51d7b4206"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[weakdeps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[extensions]
CompHENSNetworkXPlotsExt = "PyCall"

[compat]
Conda = "1"
DataFrames = "1"
DocStringExtensions = "0.9"
HiGHS = "1"
Ipopt = "1"
JLD2 = "0.4"
JuMP = "1"
Kwonly = "0.1"
MathOptInterface = "1"
Plots = "1"
PyCall = "1"
XLSX = "0.8, 0.9"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
